ingredient_research_task:
  description: >
    Conduct a comprehensive investigation of the ingredient list for {product_name}.
    Gather detailed information about each ingredient's origin, processing, 
    and potential health implications.
  expected_output: >
    A detailed ingredient database with comprehensive information, 
    including source, processing method, and initial safety assessment.
  agent: ingredient_researcher

allergen_identification_task:
  description: >
    Analyze the ingredient list for {product_name} and identify potential 
    allergens. Create a detailed risk profile for each ingredient.
  expected_output: >
    A comprehensive allergen risk assessment with detailed categorization 
    of ingredients based on allergenic potential.
  agent: allergen_identifier

additive_risk_assessment_task:
  description: >
    Investigate chemical additives in {product_name}. Assess potential 
    short-term and long-term health risks associated with each additive.
  expected_output: >
    A thorough risk assessment report detailing the safety profile of 
    each additive, including potential health concerns.
  agent: additive_risk_assessor

safety_reporting_task:
  description: >
    Synthesize findings from previous tasks. Create a comprehensive, 
    user-friendly report about the safety of {product_name}'s ingredients.
  expected_output: >
    A markdown-formatted report with clear sections on ingredient analysis, 
    allergen risks, additive safety, and overall product recommendation.
  agent: safety_reporter